import type { Metadata } from "next";
import {
  Special_Gothic_Expanded_One,
  Lexend_Deca,
  Bungee,
} from "next/font/google";
import "./globals.css";

//Fonts
const specialGothic = Special_Gothic_Expanded_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-special-gothic",
});

const lexendDeca = Lexend_Deca({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-lexend-deca",
});

const bungee = Bungee({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bungee",
});

export const metadata: Metadata = {
  title: "Technosaure Festival",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <body
        // Mettre les fonts en global
        className={`${specialGothic.variable} ${lexendDeca.variable} ${bungee.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
