import type { Metadata } from "next";
import {
  Special_Gothic_Expanded_One,
  Lexend_Deca,
  Bungee,
} from "next/font/google";
import "./globals.css";
import SmoothScroll from "./components/SmoothScroll";
import { gsap } from "gsap";
import { SplitText } from "gsap/dist/SplitText";

// Fonts
const specialGothic = Special_Gothic_Expanded_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-special-gothic",
});

const lexendDeca = Lexend_Deca({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-lexend-deca",
});

const bungee = Bungee({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bungee",
});

export const metadata: Metadata = {
  title: "Technosaure Festival",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <body
        className={`${specialGothic.variable} ${lexendDeca.variable} ${bungee.variable} antialiased overflow-x-hidden`}
      >
        <SmoothScroll />
        {children}
      </body>
    </html>
  );
}
